# Generated by Django 4.0.2 on 2022-03-22 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwords',
            old_name='pasword',
            new_name='password',
        ),
    ]
