# Generated by Django 4.0.2 on 2022-03-22 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0002_rename_pasword_passwords_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwords',
            name='captchaUser',
        ),
    ]
