# Generated by Django 4.0.3 on 2022-03-27 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
