# Generated by Django 4.0.3 on 2022-03-27 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0006_newuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newuser',
            options={'ordering': ['-id']},
        ),
    ]
