# Generated by Django 4.0.3 on 2022-04-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0007_alter_newuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwords',
            name='url',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
