# Generated by Django 4.0.3 on 2022-03-27 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='username',
        ),
        migrations.AddField(
            model_name='newuser',
            name='user',
            field=models.OneToOneField(default=5, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newuser',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
    ]
