# Generated by Django 4.0.3 on 2022-03-27 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_newuser_email_remove_newuser_last_login_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newUser',
        ),
    ]
